### ISSUE TITLE
Uncaught exception 'RuntimeException', command not found

### ISSUE THREAD

**Issue by parkroolucas** [matteosister/GitElephant#107] opened 2017-01-10 07:14 UTC
I'm receiving this error when I'm trying to use GitElephant with PHP 5.6.10:

`Fatal error: Uncaught exception 'RuntimeException' with message 'Exit code: 127 while executing: " show '-s' '--pretty=raw' '--no-color' '44f14ff'" with reason: sh: show: command not found`

This is the code I'm using:

```
<?php
  require "vendor/autoload.php";

  use GitElephant\Repository;
  use GitElephant\Objects\Branch;
  use GitElephant\Objects\Commit;
  use GitElephant\Objects\Tag;

  $repo = new Repository('../myrepo/');

  $diff = $repo->getDiff($repo->getCommit('44f14ff'), $repo->getCommit('3948f38'));

  var_dump($diff);

```

**Comment by BernhardWebstudio** [comment] 2018-06-01 12:53
Does this also occur if you change your code to `$diff = $repo->getDiff('44f14ff', '3948f38');`?
Which version are you using?

**Comment by BernhardWebstudio** [comment] 2019-01-04 19:03
Closing because not reproductible. And, probably outdated. Feel free to open a new issue

**Closed by BernhardWebstudio** 2019-01-04 19:03 UTC
