### ISSUE TITLE
Windows: should not use PHP_EOL to split Git binary output lines

### ISSUE THREAD

**Issue by MLukman** [matteosister/GitElephant#98] opened 2016-04-25 01:08 UTC
Dear sir,

On Windows machine, Git binary outputs lines using the *nix termination character "\n", not the usual "\r\n". Thus, PHP_EOL should not be used in the class method & line 

```
// GitElephant\Command\Caller::execute() line 121:
$values = array_map('rtrim', explode(PHP_EOL, $process->getOutput()));
```

It should use "\n" instead:

```
$values = array_map('rtrim', explode("\n", $process->getOutput()));
```

Thank you.

**Comment by matteosister** [comment] 2016-04-25 08:30
Hi! Thanks for reporting this...
I'm not on windows, and I do not have any windows installation to test. I will of course accept a PR, if you want to give it a try.

**Comment by MLukman** [comment] 2016-04-25 13:15
I read that you are very strict on unit testing so I tried to have my modification unit tested. But,  unit testing PHP on windows is tough. I went as far as changing the constructor of GitBinary to the following, since on windows we have `where` instead of `which`:

    public function __construct($path = null)
    {
        if (is_null($path)) {
            if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
                $path = '"'.exec('where git').'"';
            } else {
                // unix only!
                $path = exec('which git');
            }
        }
        $this->setPath($path);
    }

Here is the output anyway, which shows that there is error during TestCase::tearDown, which I assume proved that my modification passed the assertions, didn't it?

```
D:\XAMPP_5.6\htdocs\GitElephant>phpunit --bootstrap tests\bootstrap.php  --filte
r 'GitElephant\\Command\\CallerTest::testOutputLines'
git version 2.7.0.windows.1
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

E

Time: 2.11 seconds, Memory: 7.25Mb

There was 1 error:

1) GitElephant\Command\CallerTest::testOutputLines
Symfony\Component\Filesystem\Exception\IOException: Failed to remove file "C:\Us
ers\S52514\AppData\Local\Temp\gitD74A.tmp\.git\objects\58\e2e6a6898abb5ff91c3172
eca6416cadf88f30".

D:\XAMPP_5.6\htdocs\GitElephant\vendor\symfony\filesystem\Symfony\Component\File
system\Filesystem.php:172
D:\XAMPP_5.6\htdocs\GitElephant\vendor\symfony\filesystem\Symfony\Component\File
system\Filesystem.php:159
D:\XAMPP_5.6\htdocs\GitElephant\vendor\symfony\filesystem\Symfony\Component\File
system\Filesystem.php:159
D:\XAMPP_5.6\htdocs\GitElephant\vendor\symfony\filesystem\Symfony\Component\File
system\Filesystem.php:159
D:\XAMPP_5.6\htdocs\GitElephant\vendor\symfony\filesystem\Symfony\Component\File
system\Filesystem.php:159
D:\XAMPP_5.6\htdocs\GitElephant\tests\GitElephant\TestCase.php:116
D:\XAMPP_5.6\php\pear\PHPUnit\TextUI\Command.php:176
D:\XAMPP_5.6\php\pear\PHPUnit\TextUI\Command.php:129

FAILURES!
Tests: 1, Assertions: 53, Errors: 1.

```

Should I just proceed with creating the PR?

**Comment by dgorsline** [comment] 2018-08-23 15:00
This thread is very helpful.  I am attempting to get the GitElephant version 1.x unit tests running under Windows+Cygwin.

**Comment by BernhardWebstudio** [comment] 2019-01-04 19:14
This is some time ago. I cannot reproduce the issue on my device anymore. I hope it is ok when I close this issue; if not, I would like to answer @MLukman's question
> Should I just proceed with creating the PR?
with a lovely yes, please.

**Closed by BernhardWebstudio** 2019-01-04 19:14 UTC
